list<opportunity> opp = Test_Data_Factory.createProspect(1, FALSE, 'new');
//ist<opportunity> opp = Test_Data_Factory.createProspect(1, TRUE, 'new');
/*list<opportunity> opp = Test_Data_Factory.createProspect(1, TRUE, 'new', 'Demo 1 - Gate 1');
list<opportunity> opp2 = Test_Data_Factory.createProspect(1, FALSE, 'new', 'Demo 2 - Gate 3');
list<opportunity> opp3 = Test_Data_Factory.createProspect(1, TRUE, 'Gate 4', 'Demo 3 - Gate 4');
list<opportunity> opp4 = Test_Data_Factory.createProspect(1, TRUE, 'Gate 5', 'Demo 4 - Gate 5');*/
//list<opportunity> opp = Test_Data_Factory.createProspect(1, FALSE, 'Gate 4');
