/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Project_Risk_AssessmentTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Project_Risk_AssessmentTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Project_Risk_Assessment__c());
    }
}